### ISSUE TITLE
Black screen.

### ISSUE THREAD

**Issue by Ertuiop333** [HarmonyHoney/tiny_crate#1]
I'm trying to make a modification to the game, but when playing it from the editor, it shows a black screen. 

I can still hear the audio.

Please can someone tell me how to fix it because I really don't know how to debug potential visual elements that could be obscuring the view.

**Comment by Ertuiop333** [comment]
Actually, nevermind I resolved the issue : I was using the wrong renderer (went from GLES3 to GLES2).

**Comment by HarmonyHoney** [comment]
sweet! (;
